config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :discussions, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :posts, only: [:create, :show, :edit, :update, :destroy], module: :discussions
  end
  root to: "main#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  has_many :posts, dependent: :destroy

  validates :name, presence: true

  accepts_nested_attributes_for :posts

  after_create_commit -> { broadcast_prepend_to 'discussions' }
  after_update_commit -> { broadcast_replace_to 'discussions' }
  after_destroy_commit -> { broadcast_remove_to 'discussions' }

  #after_update_commit -> { broadcast_replace_to "discussions", partial: "discussions/header", locals: { discussion: self }}

  def to_param
    "#{id}-#{name.downcase.to_s[0...50]}".parameterize
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :discussion, counter_cache: true, touch:true
  belongs_to :user, default: -> { Current.user }

  has_rich_text :body

  validates :body, presence: true

  after_create_commit -> { broadcast_append_to discussion, partial: "discussions/posts/post", locals: { post: self }}
  after_update_commit -> { broadcast_replace_to discussion, partial: "discussions/posts/post", locals: { post: self }}
  after_destroy_commit -> { broadcast_remove_to discussion }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true

  has_many :discussions, dependent: :destroy
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user, if: :user_signed_in?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def set_current_user
    Current.user = current_user
  end
end

app/controllers/discussions/posts_controller.rb
module Discussions
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def show
    end

    def edit
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post.discussion, notice: "Post updated"}
        else
          format.html { render :new, status: :unprocessable_entity}
        end
      end
    end

    def create
      @post = @discussion.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to discussion_path(@discussion), notice: "Post created"}
        else
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity}
        end
      end
    end

    def destroy
      @post.destroy

      respond_to do |format|
        format.turbo_stream { } # let the callback delete the post
        format.html { redirect_to @posst.discussion, notice: "Post deleted"}
      end
    end

    private

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end

    def set_post
      @post = @discussion.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body)
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]

  def index
    @discussions = Discussion.all.order(updated_at: :desc)
  end

  def show
    @posts = @discussion.posts.all.order(created_at: :asc)
    @new_post = @discussion.posts.new
  end

  def new
    @discussion = Discussion.new
    @discussion.posts.new
  end

  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: "Discussion created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        @discussion.broadcast_replace(partial: "discussions/header", locals: { discussion: @discussion })
        format.html { redirect_to @discussion, notice: "Discussion updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @discussion.destroy!
        format.html { redirect_to discussions_path, notice: 'Discussion removed' }
      end
    end
  end

  private

  def discussion_params
    params.require(:discussion).permit(:name, :closed, :pinned, posts_attributes: :body)
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/discussions/_discussion.html.erb
    <li id="<%= dom_id(discussion) %>">
      <a href="#" class="block hover:bg-gray-50">
        <div class="px-4 py-4 flex items-center justify-between sm:px-6">
          <div class="min-w-0 flex-1 sm:flex sm:items-center">
            <div class="truncate">
              <div class="flex text-sm">
                <%= link_to discussion.name, discussion, class: "block font-medium text-indigo-600 truncate" %>
                <% if discussion.pinned? %>
                  <p class="ml-1 flex-shrink-0 font-normal text-gray-500">
                    Pinned
                  </p>
                <% end %>
                <% if discussion.closed? %>
                  <p class="ml-1 flex-shrink-0 font-normal text-gray-500">
                    Closed
                  </p>
                <% end %>
              </div>
              <div class="mt-2 flex">
                <div class="flex items-center text-sm text-gray-500">
                  <!-- Heroicon name: solid/calendar -->
                  <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd" />
                  </svg>
                  <p>
                    Updated
                    <time datetime="2020-01-07">January 7, 2020</time>
                  </p>
                </div>
              </div>
            </div>
            
          </div>
          <div class="flex">
            <div class="w-6 ml-5 flex-shrink-0">
              <%= link_to "Edit", edit_discussion_path(discussion) %>
            </div>
            <div class="w-8 ml-5 flex-shrink-0">
              <%= button_to "Delete", discussion, method: :delete %>
            </div>
          </div>
        </div>
      </a>
    </li>

app/views/discussions/_form.html.erb
<div>
  <div class="md:grid md:grid-cols-4 md:gap-6">
    <div class="md:col-span-1">
    </div>
    <div class="mt-5 md:mt-0 md:col-span-2">
      <%= form_with(model:discussion) do |form| %>
        <% if discussion.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(discussion.errors.count, "error") %> prevented this discussion from being saved:</h2>
            <ul>
              <% discussion.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="shadow sm:rounded-md sm:overflow-hidden">
          <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
            <div class="grid grid-cols-3 gap-6">
              <div class="col-span-3 sm:col-span-2">
                <%= form.label :name, class: "block text-sm font-medium text-gray-700" %>
                <div class="mt-1 flex rounded-md shadow-sm">
                  <%= form.text_field :name, placeholder: "How do I...?", class: "focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-none rounded-r-md sm:text-sm border-gray-300" %>
                </div>
              </div>
            </div>

            <div class="mt-4 space-y-4">
              <div class="flex items-start">
                <div class="flex items-center h-5">
                  <%= form.check_box :pinned, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded" %>                    
                </div>
                <div class="ml-3 text-sm">
                  <%= form.label :pinned, class: "font-medium text-gray-700" %>
                  <p class="text-gray-500">Pin this discussion.</p>
                </div>
              </div>
              <div class="flex items-start">
                <div class="flex items-center h-5">
                  <%= form.check_box :closed, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded" %>
                </div>
                <div class="ml-3 text-sm">
                  <%= form.label :closed, class: "font-medium text-gray-700" %>
                  <p class="text-gray-500">Mark this discussion as closed.</p>
                </div>
              </div>
              <% if discussion.new_record? %>
          <%= form.fields_for :posts do |p| %>
            <%= p.rich_text_area :body, placeholder: "Kickoff the discussion" %>
          <% end %>
        <% end %>
            </div>
          </div>
        </div>

        
      
        <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
          <%= form.submit class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        </div>
      </div>
      
    </div>
    <% end %>
  </div>
</div>

app/views/discussions/_header.html.erb
<%= turbo_frame_tag dom_id(discussion) do %>
  <div class="md:flex md:items-center md:justify-between md:space-x-4 xl:border-b xl:pb-6">  
    <div>
      <h1 class="text-2xl font-bold text-gray-900"><%= discussion.name %></h1>
      <p class="mt-2 text-sm text-gray-500">
        <% if discussion.pinned %>
          <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
            Pinned
          </span>
        <% end %>
        <% if discussion.closed %>
          <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800">
            Closed
          </span>
        <% end %>
      </p>
    </div>
    <div class="mt-4 flex space-x-3 md:mt-0">
        <%= button_to "Edit", edit_discussion_path(discussion), class: "inline-flex justify-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900" %>
        <%= button_to "Delete", discussion, method: :delete, class: "inline-flex justify-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900", data: { confirm: "Are you sure? This cannot be undone."} %>
    </div>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
  <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
    <div class="ml-4 mt-2">
      <h3 class="text-lg leading-6 font-medium text-gray-900">
        Edit Discussion
      </h3>
    </div>
  </div>
</div>

<%= turbo_frame_tag dom_id(@discussion) do %>
  <%= render("form", discussion: @discussion) %>
  <%= link_to "Cancel", @discussion %>
<% end %>

app/views/discussions/index.html.erb
<%= turbo_stream_from 'discussions' %>
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
  <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
    <div class="ml-4 mt-2">
      <h3 class="text-lg leading-6 font-medium text-gray-900">
        Discussions
      </h3>
    </div>
    <div class="ml-4 mt-2 flex-shrink-0">
      <%= link_to new_discussion_path, class: "relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" do %>
        New Discussion
      <% end %>
    </div>
  </div>
</div>

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="bg-white shadow overflow-hidden sm:rounded-md">
  <ul id="discussions" role="list" class="divide-y divide-gray-200">
    <%= render @discussions %>
  </ul>
</div>

app/views/discussions/new.html.erb
<div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
  <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
    <div class="ml-4 mt-2">
      <h3 class="text-lg leading-6 font-medium text-gray-900">
        New Discussion
      </h3>
    </div>
  </div>
</div>

<%= render("form", discussion: @discussion) %>

app/views/discussions/posts/_form.html.erb
<%= turbo_frame_tag "#{dom_id(post)}_form", target: "_top" do %>
  <%= form_with(model: [post.discussion, post]) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2>prohibited this post from being saved:</h2>
        <ul>
          <%= post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :body, class: "" %>
      <%= form.rich_text_area :body, placeholder: "Add your comment", autofocus: true %>
    </div>
    <div>
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/discussions/posts/_header.html.erb
<div class="relative">
  <img class="h-10 w-10 rounded-full bg-gray-400 flex items-center justify-center ring-8 ring-white" src="https://images.unsplash.com/photo-1520785643438-5bf77931f493?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=256&h=256&q=80" alt="">

  <span class="absolute -bottom-0.5 -right-1 bg-white rounded-tl px-0.5 py-px">
    <!-- Heroicon name: solid/chat-alt -->
    <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
      <path fill-rule="evenodd" d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z" clip-rule="evenodd" />
    </svg>
  </span>
</div>
<div class="min-w-0 flex-1">
  <div>
    <div class="text-sm">
      <a href="#" class="font-medium text-gray-900"><%= post.user.username %></a>
    </div>
      <p class="mt-0.5 text-sm text-gray-500">
        Posted on: <%= post.created_at %>
      </p>
    </div>
  </div>

app/views/discussions/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
<li>
  <div class="relative pb-8">
    <span class="absolute top-5 left-5 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
    <div class="relative flex items-start space-x-3">
      <div class="relative">
        <img class="h-10 w-10 rounded-full bg-gray-400 flex items-center justify-center ring-8 ring-white" src="https://images.unsplash.com/photo-1520785643438-5bf77931f493?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=256&h=256&q=80" alt="">
        <span class="absolute -bottom-0.5 -right-1 bg-white rounded-tl px-0.5 py-px">
          <!-- Heroicon name: solid/chat-alt -->
          <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z" clip-rule="evenodd" />
          </svg>
        </span>
      </div>
      <div class="min-w-0 flex-1">
        <div>
          <div class="text-sm">
            <a href="#" class="font-medium text-gray-900"><%= post.user.username %></a>
          </div>
          <p class="mt-0.5 text-sm text-gray-500">
            Posted on: <%= post.created_at %>
          </p>
        </div>
      
        <div class="mt-2 text-sm text-gray-700">
          <p>
            <%= post.body %>
          </p>
        </div>
      </div>
      <div class="mt-4 flex space-x-1 md:mt-4">
        <%= link_to "Edit", edit_discussion_post_path(post.discussion, post), data: { turbo_frame: dom_id(post) }, class: "inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        <%= button_to "Delete", discussion_post_path(post.discussion, post), method: :delete, class: "inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </div>  
      
    </div>
  </div>
</li>
<% end %>

app/views/discussions/posts/create.turbo_stream.erb
<%= turbo_stream.replace "new_post_form" do %>
  <%= render partial: "discussions/posts/form", formats: :html, locals: { post: @post } %>
<% end %>

app/views/discussions/posts/edit.html.erb
<h1>Edit post</h1>
<%= turbo_frame_tag dom_id(@post) do %>
  <%= render(partial: "discussions/posts/header", locals: { post: @post }) %>
  <%= render("form", post: @post) %>
  <%= link_to "Back", discussion_post_path(@post.discussion, @post) %>  
<% end %>

app/views/discussions/posts/show.html.erb
<%= render partial: "discussions/posts/post", locals: { post: @post } %>

app/views/discussions/show.html.erb
<%= turbo_stream_from @discussion %>
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
  <div class="max-w-3xl mx-auto">
    <%= render(partial: "discussions/header", locals: { discussion: @discussion }) %>

    <div class="flow-root mt-4">
      <ul id="posts" role="list" class="-mb-8">
        <%= render partial: "discussions/posts/post", collection: @posts %>
      </ul>
    </div>

    <div id="<%= dom_id(@new_post) %>" class="mt-12">
      <%= render("discussions/posts/form", post: @new_post) %>
    </div>

  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireForums</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render("shared/flash") %>

    <%= render("shared/navigation") %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info mb-4" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning mb-4" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
    <header class="bg-indigo-600">
      <nav class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" aria-label="Top">
        <div class="w-full py-6 flex items-center justify-between border-b border-indigo-500 lg:border-none">
          <div class="flex items-center">
            <%= link_to(root_path, class: "navbar-brand") do %>
              <span class="sr-only">Hotwire Forums</span>
              <img class="h-10 w-auto" src="https://tailwindui.com/img/logos/workflow-mark.svg?color=white" alt="">
            <% end %>
            <div class="hidden ml-10 space-x-8 lg:block">
              <%= link_to "Discussions", discussions_path, class: "text-base font-medium text-white hover:text-indigo-50" %>
            </div>
          </div>
          <div class="ml-10 space-x-4">
            <% if user_signed_in? %>
              <%= link_to Current.user.username, edit_user_registration_path, class: "inline-block bg-indigo-500 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white hover:bg-opacity-75" %>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "inline-block bg-white py-2 px-4 border border-transparent rounded-md text-base font-medium text-indigo-600 hover:bg-indigo-50" %>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path, class: "inline-block bg-indigo-500 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white hover:bg-opacity-75" %>
              <%= link_to "Log In", new_user_session_path, class: "inline-block bg-indigo-500 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white hover:bg-opacity-75" %>
            <% end %>
          </div>
        </div>
        <div class="py-4 flex flex-wrap justify-center space-x-6 lg:hidden">
          <a href="#" class="text-base font-medium text-white hover:text-indigo-50" key="Solutions">
            Solutions
          </a>

          <a href="#" class="text-base font-medium text-white hover:text-indigo-50" key="Pricing">
            Pricing
          </a>
        </div>
      </nav>
    </header>